language: node_js
node_js:
  - 10
branches:
  only:
    - master
install:
  - yarn
  - yarn global add codecov
script:
  - yarn test
  - codecov
  - yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: master